# Generated by Django 4.2.5 on 2023-09-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
