# Generated by Django 4.2.5 on 2023-10-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0002_alter_problem_options_alter_problem_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="memory_limit",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="time_limit",
            field=models.IntegerField(null=True),
        ),
    ]
